import React, { Component } from "react"
import { Navigation }  from '../components/navigation'

class Terminos extends Component {
    render(){
        return(
          
        <>
         <Navigation />
         <div className="container">
            <div className="row py-5 mt-4 justify-content-center">
              
              
        
                
                <div className="col-md-7 col-lg-9 terminos">
                    <h2 className="centrar" >TERMINOS Y CONDICIONES</h2>
                
                    <p className="aboutus">&nbsp;</p>
                    <p className="aboutus">Las presentes condiciones generales (en adelante CONDICIONES), regulan los términos y condiciones de acceso y uso de la Plataforma TELECONSUL&nbsp; que pone a disposición de la Cámara de Comercio Empresarial&nbsp; con RUC N° 20600836910 y domicilio en Calle 2 de Mayo 516, Miraflores- Lima (en adelante “CCE”) con el alcance y hasta los límites que se definen en estas CONDICIONES, las cuales el USUARIO debe leer, entender y aceptar para hacer uso del servicio y obtener el asesoramiento que se brinda a través del mismo.&nbsp;</p>
                    <p className="aboutus">CCE se reserva la facultad de modificar, en cualquier momento la presentación y configuración de la Plataforma TELECONSUL, así como de sus contenidos y servicios que en él se incorporan. EL USUARIO reconoce y acepta que en cualquier momento CCE pueda interrumpir, desactivar y/o cancelar cualquiera de los contenidos y Servicios que se integran en la Plataforma TELECONSUL.&nbsp;</p>
                    <p className="aboutus">CCE, brinda una herramienta informática que permita a sus usuarios registrados acceder a un registro para contactarse con médicos terceros quienes prestarán sus servicios de salud directamente a los usuarios y no a CCE, siendo la Plataforma TELECONSUL, sólo una herramienta para acceder a un registro de profesionales que ofrecen sus servicio de forma voluntaria en tele orientación para lo cual toma conocimiento que los profesionales no tienen relación laboral o de dependencia con CCE, sino que son médicos quienes han decidido brindar su tiempo y conocimiento para orientar a los Usuarios que soliciten asesoría;</p>
                    <p className="aboutus">Todos los PROFESIONALES, que ofrecen y/o prestan sus servicios a través de TELECONSUL son profesionales independientes, que no tienen ninguna relación laboral con CCE y son totalmente responsables por los servicios que ofrecen. Bajo ninguna circunstancia se entenderá que los PROFESIONALES son empleados, afiliados, agentes, representantes, o de cualquier otra manera relacionados a CCE o cualquiera de sus afiliadas. En este sentido, se acuerda expresamente que CCE no forma parte, ni adquiere obligación alguna derivada de, la prestación de servicios por parte de los PROFESIONALES a USUARIOS. CCE no diagnostica ni realiza consultas y por ningún motivo interfiere con la práctica profesional que ejercen los PROFESIONALES listados en TELECONSUL. Todos los PROFESIONALES son responsables de los servicios e indicaciones que prestan y que ofrecen y también del cumplimiento de las normatividades aplicables para el correcto ejercicio de su profesión. CCE ni EL SITIO ni cualquier medio por el cual tuvo acceso al SITIO es responsable por las prescripciones, consejos, indicaciones o servicios profesionales que obtuvo de los PROFESIONALES a través de los SERVICIOS que se ofrecen en TELECONSUL.</p>
                    <p className="aboutus">CCE, así como cualquier persona relacionada y/o afiliada a CCE, incluyendo, sin limitar, directores, apoderados, representantes, administradores, empleados, accionistas y/o agentes, presentes o anteriores, no serán responsables de errores u omisiones en los contenidos de TELECONSUL. Asimismo, no serán responsables, bajo ningún caso o circunstancia, por datos y/o perjuicios que se pudieren causar a USUARIOS y/o PROFESIONALES derivado del uso de la Plataforma.</p>
                    <p className="aboutus">En ningún caso CCE tendrá responsabilidad derivada de violación del secreto profesional por parte de los PROFESIONALES, ni de cualquier daño y/o perjuicio que sean consecuencia directa de una lesión o daño causado por el tratamiento a un USUARIO, por parte de un PROFESIONAL. USUARIOS y PROFESIONALES, mediante su aceptación a los presentes términos y condiciones, se obligan expresamente a sacar en paz y a salvo e indemnizar (incluyendo el pago de honorarios de abogados) a CCE, así como a cualquier persona relacionada y/o afiliada a CCE, incluyendo, sin limitar, directores, apoderados, representantes, administradores, empleados, accionistas y/o agentes, presentes o anteriores, de cualquier responsabilidad que derive, o pudiere derivar, del uso de TELECONSUL, o de cualquier servicio derivado de dicho uso, incluyendo de manera enunciativa, más no limitativa, cualesquiera contingencias legales, fiscales, laborales, administrativas, civiles, penales, financieras, de salud o de cualquier otra índole, cualesquiera reclamación, demanda, juicio, acto, hecho u omisión que represente o pudiera representar una responsabilidad a cargo de CCE, o a cargo de personas relacionadas y/o afiliadas.</p>
                    <p className="aboutus">CCE no se hace responsable de las acciones, inacciones o contenido vertido durante la consejería especializada. EL USUARIO admite explícitamente que la Plataforma TELECONSUL es un medio para permitir que un médico que esté registrado en la Plataforma TELECONSUL pueda ofrecer de manera gratuita sus servicios de consejería especializada. CCE no tiene ninguna implicación en la transacción entre los USUARIOS y los médicos especialistas. CCE, no garantiza la calidad ni la seguridad de los servicios provistos por los PROFESIONALES, tampoco asegura la disponibilidad de PROFESIONALES. La tele consulta derivado del uso de la Plataforma TELECONSUL, será sólo para orientación que no reemplazan en ninguna forma a una consulta fisica. NO SE REALIZAN ATENCIONES DE EMERGENCIAS O URGENCIAS MÉDICAS, ni mediante la Plataforma TELECONSUL ni por solicitudes que realicen LOS USUARIOS a los médicos que ofrezcan sus servicios gratuitos mediante la Plataforma TELECONSUL. En caso de emergencias o urgencias médicas se recomienda dirigirse a la Emergencia o Urgencia del Establecimiento de Salud más cercano.&nbsp;</p>
                    <h3>USUARIO DE LA PLATAFORMA TELECONSUL Y SU REGISTRO</h3>
                    <p className="aboutus">El USUARIO, es aquella persona que accede vía web o descarga en su dispositivo móvil la Plataforma TELECONSUL. Este USUARIO puede ser una persona natural que requiera contactar con un PROFESIONAL registrado en la Plataforma TELECONSUL que va prestar un servicio de orientación a un usuario en la Plataforma TELECONSUL. Este aplicativo, respecto a quienes deseen brindar el servicio de tele orientación, sólo está restringido al uso de PROFESIONALES que cuenten con una colegiatura hábil en su colegio profesional y con un registro nacional de especialidad de ser el caso, y cumpla con todas las condiciones necesarias para la prestación de sus servicios profesionales. La utilización de los servicios de la Plataforma TELECONSUL requiere la previa inscripción por parte del USUARIO, tanto del USUARIO como del PROFESIONAL, lo cual conlleva a la aceptación de los términos y condiciones aquí descritos; además de la autorización de aceptación de la inscripción para ser considerado USUARIO registrado. El PROFESIONAL registrado, en caso de los PROFESIONALES, es aquel con colegiatura, registro de especialidad y estado de habilitado en su Colegio PROFESIONAL respectivo correspondiente en el territorio según corresponda, que ha solicitado su registro en la Plataforma TELECONSUL. El PROFESIONAL que solicita inscripción como tal en la Plataforma TELECONSUL declara cumplir con todas las condiciones legales para el ejercicio de su profesión según la exigencia de la normativa vigente en el momento de la solicitud de inscripción. Asimismo, informará a CCE en caso siendo ya un PROFESIONAL registrado ya no cumpla con las condiciones de habilidad para la prestación de sus servicios profesionales. El PROFESIONAL será el único responsable por el incumplimiento de lo dispuesto en este párrafo. EL PROFESIONAL puede usar la Plataforma TELECONSUL para facilitar la conexión con los usuarios que se hayan registrado en la Plataforma TELECONSUL. Estos USUARIOS comparten la responsabilidad de asegurarse de que las prestaciones de orientación realizada a través de la Plataforma TELECONSUL se realizan sin complicaciones, de buena fe y aportan valor.</p>
                    <p className="aboutus">Tomar en cuenta que La Plataforma TELECONSUL es una plataforma digital que intermedia entre usuarios, tanto los solicitantes como los PROFESIONALES por lo que, los Servicios, las opiniones, diagnósticos, tratamientos o recetas, que sean emitidas por los PROFESIONALES, no serán en ningún caso responsabilidad de CCE. El tratamiento de los datos personales obtenidos de los Usuarios será usado de manera confidencial. Cabe resaltar que toda la información otorgada por los USUARIOS será tratada de forma confidencial y no será compartida con terceros, salvo para los fines adicionales que el USUARIO lo consienta. En este sentido, la Plataforma TELECONSUL garantiza la privacidad y seguridad de la información brindada previa y durante la realización de la orientación.</p>
                    <p className="aboutus">&nbsp;</p>
                    <h3>OBLIGACIONES DEL USUARIO:&nbsp;</h3>
                    <p className="aboutus">Serán obligaciones del USUARIO, las contenidas en las presentes CONDICIONES: El USUARIO con la solicitud de registro de inscripción declara que todos los datos en él son veraces, siendo el USUARIO el único responsable de inexactitudes diligenciadas y de los perjuicios causados a terceros por esa causa. Así, en el evento de presentarse suplantación de la identidad, EL USUARIO no tendrá derecho a indemnización alguna por parte de CCE. En caso EL USUARIO tenga la sospecha de suplantación debe informar de manera inmediata a CCE a través del correo info@camarahelp.com, para la toma de medidas respectivas. EL USUARIO se compromete a informar a CCE cualquier irregularidad que observe en el funcionamiento de la Plataforma TELECONSUL, directamente o a través del correo info@camarahelp.com. EL USUARIO se abstendrá de efectuar maniobras ilícitas o fraudulentas, que puedan afectar derechos o intereses de CCE o de terceros, especialmente de los datos personales que acceda o registre en la Plataforma TELECONSUL. EL USUARIO está prohibido del uso o aplicación de cualesquiera recursos técnicos, lógicos o tecnológicos por virtud de los cuales pueda beneficiarse, directa o indirectamente, con o sin lucro, de la explotación no autorizada de los contenidos y servicios de la Plataforma TELECONSUL.&nbsp;</p>
                    <p className="aboutus">EL USUARIO se abstendrá de realizar cualquier actividad tendiente a sobrecargar o inutilizar la Plataforma TELECONSUL. EL USUARIO se encuentra prohibido de realizar registros, grabaciones u otros mecanismos equivalentes en formato de audio, video u otros similares de las interacciones que se realicen en la Plataforma TELECONSUL, sin autorización expresa de CCE. Cualquier documento obtenido en contravención a la presente disposición será considerado nulo y sin valor legal. EL USUARIO que desee registrar datos personales de terceros deberá contar con la autorización de ellos, siendo su exclusiva responsabilidad para ello. En caso se tenga la sospecha o confirme la vulneración de alguna de estas obligaciones o las demás señaladas en las CONDICIONES, CCE se reserva el derecho de suspender o anular el registro del USUARIO y PROFESIONAL en la Plataforma TELECONSUL, y en caso de un acto ilícito realizar la denuncia respectiva ante la autoridad competente.</p>
                    <h3>RESPONSABILIDADES EN EL APLICATIVO TELECONSUL</h3>
                    <p className="aboutus">El contenido de la comunicación vertida durante la tele orientación que realice el PROFESIONAL especialista como respuesta a las consultas del usuario de TELECONSUL, serán de su exclusiva responsabilidad. En cualquier momento EL USUARIO podrá solicitar la baja de su registro o la solicitud de esta del Banco de Datos Personales de la Plataforma TELECONSUL. En cuyo caso, los datos personales registrados –previamente anonimizados-, sólo se mantendrán para fines históricos hasta 10 años luego de la solicitud de baja, no pudiendo ser accesible a otros USUARIOS. EL USUARIO, en el evento de manifestar su intención de ser retirados del banco de datos de la Plataforma TELECONSUL, aceptan que la información brindada y registrada por este continúan siendo de su responsabilidad. CCE no se responsabiliza por la calidad, interrupción, suspensión o cancelación del acceso a la Plataforma TELECONSUL. La información suministrada por EL USUARIO, tanto Médico como el usuario en salud que solicite la orientación en la Plataforma TELECONSUL es de su exclusiva responsabilidad. El USUARIO es consciente, y acepta voluntariamente, que el uso de la Plataforma TELECONSUL tiene lugar, en todo caso, bajo su responsabilidad, por lo cual adoptará todas aquellas medidas que fuesen necesarias a los efectos de minimizar los riesgos, incluyendo la adopción de las medidas de seguridad que fueren necesarias para garantizar procedimientos antivirus y de recuperación de datos. EL USUARIO podrá acceder a la información relativa al tratamiento de sus datos personales —tanto generales como sensibles— ingresando a la política de privacidad de la Plataforma TELECONSUL. El tratamiento de los datos personales de EL USUARIO se realiza en el marco de la Ley N° 29733, su reglamento y normas conexas, así como de la Emergencia Nacional declarada por Decreto Supremo Nº 044-2020-PCM, exclusivamente para fines vinculados a materias de salud.</p>
                    <p className="aboutus">Los datos serán tratados de forma confidencial y no serán compartidos con terceros. Sin embargo, CCE no asume responsabilidad derivada del uso inadecuado de los datos contenidos en la Plataforma TELECONSUL por parte de los USUARIOS, ni del uso autorizado por éstos a terceros.</p>
                </div>
                </div>
            </div>
        </>
        )
    }
}
export default Terminos

